/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playermp3;

import java.io.File;
import java.io.RandomAccessFile;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author Umer
 */
public class GeneralUserAccount extends javax.swing.JFrame {

    private static final String Namepatern = "[A-Za-z]{3,15}$";
    private static final String Passwordpatern = "^(?=(.*[A]).{1})(?=(.*[0-9]).{3})(?=(.*[@#$%^&+]){1})(?=(.*[a-z]){6})(?=(.*[=]){1})(?=\\S+$).{12,}$";
//"^(?=(.*[0-9]).{3})(?=(.*[a-z]){3})(?=(.*[@#$%^&+]){1})(?=(.*[=]){1})(?=\\S+$).{8,}$";
      
    /**
     * Creates new form GeneralUserAccount
     */
    public GeneralUserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mesage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JPasswordField();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("General User Password");

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Sign In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("        General User Account ");

        mesage.setForeground(new java.awt.Color(255, 0, 0));
        mesage.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("General User Password");

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Sign In");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(44, 44, 44)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesage, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(103, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(mesage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(79, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        // TODO add your handling code here:
//
//        boolean check=false;
//        boolean check1=false;
//
//        mesage.setVisible(true);
//        mesage.setText("");
//
//        String password= jTextField4.getText();
//
//        if (password.matches(Passwordpatern))
//        {
//            check1=true;
//        }
//        else
//        {
//            mesage.setText("Password Wrong ");
//            //   mesage1.setText("Passwords Must be 12 digits Long Starting with A- then + 3 numbers a +special character $ +6 letters + Always ends with = sign");
//
//        }
//        if (check1==true){
//            //  String file = "generaluser.txt";
//
//            try {
//                boolean coorect  = checkuser(password);
//                if (coorect)
//                {
//                    String datetoday = getdate(password);
//                    Date today = Calendar.getInstance().getTime();
//                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                    String dt =datetoday;
//                    Calendar c = Calendar.getInstance();
//                    c.setTime(sdf.parse(dt));
//                    c.add(Calendar.DATE, 0);  // number of days to add
//                    dt = sdf.format(c.getTime());
//                    sdf.setTimeZone(c.getTimeZone());
//                    sdf.setCalendar(c);
//                    Date day = c.getTime();
//                    String reportDate = sdf.format(day);
////                    System.out.println(reportDate);
//
//                    long diff = day.getTime() - today.getTime();
//                    long diffSeconds = diff / 1000 % 60;
//                    long diffMinutes = diff / (60 * 1000) % 60;
//                    long diffHours = diff / (60 * 60 * 1000);
//                    int diffInDays = (int) ((day.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
//
//                    if (diffInDays > 1) {
//                        System.err.println("Difference in number of days (2) : " + Integer.toString((int)diffInDays));
//
//                        GeneralUserAccountMenu admin = new GeneralUserAccountMenu("Total Days Left In You Trial "+Integer.toString((int)diffInDays));
//
//                        admin.setVisible(true);
////   ListMenu list = new ListMenu();
//                      //  list.setVisible(true);
//
//                        dispose();
//
//                    } else if (diffHours > 24) {
//
//                        System.err.println(">24");
//                        GeneralUserAccountMenu admin = new GeneralUserAccountMenu("Total Hours Left In You Trial "+Integer.toString((int)diffHours));
//
//                        admin.setVisible(true);
//                        ListMenu list = new ListMenu();
//                        list.setVisible(true);
//
//                        dispose();
//
//                    } else if ((diffHours == 24) && (diffMinutes >= 1)) {
//                        System.err.println("minutes");
//                        //  mesage.setText("Welcome");
//                        GeneralUserAccountMenu admin = new GeneralUserAccountMenu("Total Minutes Left In You Trial "+Integer.toString((int)diffMinutes));
//
//                        admin.setVisible(true);
//                        ListMenu list = new ListMenu();
//                        list.setVisible(true);
//
//                        dispose();
//
//                    }
//                    else
//                    {
//                        mesage.setText("Your Teial Period of 45 Days Are Over...");
//                    }
//
//                }
//                else
//                {
//                    mesage.setText("Wrong Name or Password!  Enter Again");
//
//                }
//
//            }
//            catch (Exception e)
//            {
//                System.out.println(e);
//                mesage.setText(e.toString());
//            }
//        }
//
        }

        public String getdate(String password)
        {
            try{
                File fXmlFile = new File("user.xml");
                DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
                DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
                Document doc = dBuilder.parse(fXmlFile);

                doc.getDocumentElement().normalize();

                System.out.println("Root element :" + doc.getDocumentElement().getNodeName());

                NodeList nList = doc.getElementsByTagName("USER");

                System.out.println("----------------------------");

                for (int i=0;i<100;i++){
                    Node nNode = nList.item(i);

                    System.out.println("\nCurrent Element :" + nNode.getNodeName());

                    if (nNode.getNodeType() == Node.ELEMENT_NODE) {

                        Element eElement = (Element) nNode;

                        //System.out.println("NAME : " + eElement.getElementsByTagName("NAME").item(0).getTextContent());
                        //System.out.println("PASSWORD : " + eElement.getElementsByTagName("PASSWORD").item(0).getTextContent());
                        //System.out.println("Salary : " + eElement.getElementsByTagName("salary").item(0).getTextContent());
                        //String id = eElement.getElementsByTagName("ID").item(0).getTextContent();

                        String p =  eElement.getElementsByTagName("PASSWORD").item(0).getTextContent();
                        String d =  eElement.getElementsByTagName("DATE").item(0).getTextContent();

                        if ( p.equals(password))
                        {
                            //   dispose();

                            return d;

                        }

                    }
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            return "";

        }

        public boolean checkuser(String pass)
        {
            try{
                File fXmlFile = new File("user.xml");
                DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
                DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
                Document doc = dBuilder.parse(fXmlFile);

                doc.getDocumentElement().normalize();

                System.out.println("Root element :" + doc.getDocumentElement().getNodeName());

                NodeList nList = doc.getElementsByTagName("USER");

                System.out.println("----------------------------");
                for (int i=0;i<100;i++){
                    Node nNode = nList.item(i);

                    System.out.println("\nCurrent Element :" + nNode.getNodeName());

                    if (nNode.getNodeType() == Node.ELEMENT_NODE) {

                        Element eElement = (Element) nNode;

                        //System.out.println("NAME : " + eElement.getElementsByTagName("NAME").item(0).getTextContent());
                        //System.out.println("PASSWORD : " + eElement.getElementsByTagName("PASSWORD").item(0).getTextContent());
                        //System.out.println("Salary : " + eElement.getElementsByTagName("salary").item(0).getTextContent());
                        //String id = eElement.getElementsByTagName("ID").item(0).getTextContent();

                        String p =  eElement.getElementsByTagName("PASSWORD").item(0).getTextContent();
                        System.out.println(p);
                        if ( p.equals(pass))
                        {
                            //   dispose();

                            return true;

                        }

                    }
                }
            }

            catch (Exception e) {
                e.printStackTrace();
            }
            return false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButton2ActionPerformed
  boolean check=false;
        boolean check1=false;

        mesage.setVisible(true);
        mesage.setText("");

        String password= jTextField4.getText();

        if (password.matches(Passwordpatern))
        {
            check1=true;
        }
        else
        {
            mesage.setText("Password Wrong ");
            //   mesage1.setText("Passwords Must be 12 digits Long Starting with A- then + 3 numbers a +special character $ +6 letters + Always ends with = sign");

        }
        if (check1==true){
            //  String file = "generaluser.txt";

            try {
                boolean coorect  = checkuser(password);
                if (coorect)
                {
                    String datetoday = getdate(password);
                    Date today = Calendar.getInstance().getTime();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String dt =datetoday;
                    Calendar c = Calendar.getInstance();
                    c.setTime(sdf.parse(dt));
                    c.add(Calendar.DATE, 0);  // number of days to add
                    dt = sdf.format(c.getTime());
                    sdf.setTimeZone(c.getTimeZone());
                    sdf.setCalendar(c);
                    Date day = c.getTime();
                    String reportDate = sdf.format(day);
               //     System.out.println(reportDate);

                    long diff = day.getTime() - today.getTime();
                    long diffSeconds = diff / 1000 % 60;
                    long diffMinutes = diff / (60 * 1000) % 60;
                    long diffHours = diff / (60 * 60 * 1000);
                    int diffInDays = (int) ((day.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

                    if (diffInDays > 1) {
                        System.err.println("Difference in number of days : " + Integer.toString((int)diffInDays));

                        ShowDisclaimer admin = new ShowDisclaimer("Total Days Left In You Trial "+Integer.toString((int)diffInDays));

                        admin.setVisible(true);
                   

                        dispose();

                    } else if (diffHours > 24) {

                        System.err.println(">24");
                        ShowDisclaimer admin = new ShowDisclaimer("Total Hours Left In You Trial "+Integer.toString((int)diffHours));

                        admin.setVisible(true);

                        dispose();

                    } else if ((diffHours == 24) && (diffMinutes >= 1)) {
                        System.err.println("minutes");
                        //  mesage.setText("Welcome");
                        ShowDisclaimer admin = new ShowDisclaimer("Total Minutes Left In You Trial "+Integer.toString((int)diffMinutes));

                        admin.setVisible(true);

                        dispose();

                    }
                    else
                    {
                        mesage.setText("Your Teial Period of 45 Days Are Over...");
                    }

                }
                else
                {
                    mesage.setText("Wrong Name or Password!  Enter Again");

                }

            }
            catch (Exception e)
            {
                System.out.println(e);
                mesage.setText(e.toString());
            }
        }


    }//GEN-LAST:event_jButton4jButton2ActionPerformed

    
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralUserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField jTextField4;
    private javax.swing.JLabel mesage;
    // End of variables declaration//GEN-END:variables
}